# Run the local Mission (see Dockerfile) with a mongodb
#
# After run the web application is available at http://localhost:3000
#
# Volumes are:
#
# * `./db/` is the persistent mongo database.
#   It is used (shared) by the mongo docker.
# * `./out/` is the submission directory
#   It is provided so the admin can manage/grep/whatever the directory.

version: '2'
services:
        web:
                build: .
                ports:
                        - "3000:3000"
                volumes:
                        - ./out:/missions/out
                depends_on:
                        - mongo
                        - runner
        mongo:
                image: mongo:2
                volumes:
                        - ./db:/data/db

        # The runner looks at the `out` directory and trigger runners for them
        runner:
                build: share/runner
                volumes:
                        - ./out:/out
                        - /var/run/docker.sock:/var/run/docker.sock
                depends_on:
                        - worker

        # The worker image is executed by the `runner`
        worker:
                build: share/worker
                image: mission_worker
